import Menu from "@/components/Menu";
import type { Metadata } from "next";
import { useSession } from "next-auth/react";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const Layout: React.FC<Props> = ({ children }) => {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status === "loading" || router.pathname === "/") {
    return <div className={inter.className}>{children}</div>; // Se não estiver autenticado ou ainda estiver carregando e a rota for a de login, renderiza apenas o conteúdo da página.
  }

  return (
    <div className={inter.className}>
      <Menu username={session?.user.name ?? ""} />
      <div className="p-4 sm:ml-64">{children}</div>
    </div>
  );
};

export default Layout;
